kind = "web"
previewPath = "/"
title = "Appflexor"
version = "1.0.0"
id = "artifacts/appflexor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18232

[services.development]
run = "pnpm --filter @workspace/appflexor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/appflexor", "run", "build" ]
publicDir = "artifacts/appflexor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18232"
BASE_PATH = "/"
