const COUNTRIES = [
  { id: "afghanistan", name: "Afghanistan" },
  { id: "aland_islands", name: "Aland Islands" },
  { id: "albania", name: "Albania" },
  { id: "algeria", name: "Algeria" },
  { id: "american_samoa", name: "American Samoa" },
  { id: "andorra", name: "Andorra" },
  { id: "angola", name: "Angola" },
  { id: "anguilla", name: "Anguilla" },
  { id: "antarctica", name: "Antarctica" },
  { id: "antigua_and_barbuda", name: "Antigua and Barbuda" },
  { id: "argentina", name: "Argentina" },
  { id: "armenia", name: "Armenia" },
  { id: "aruba", name: "Aruba" },
  { id: "australia", name: "Australia" },
  { id: "austria", name: "Austria" },
  { id: "azerbaijan", name: "Azerbaijan" },
  { id: "bahamas", name: "Bahamas" },
  { id: "bahrain", name: "Bahrain" },
  { id: "bangladesh", name: "Bangladesh" },
  { id: "barbados", name: "Barbados" },
  { id: "belarus", name: "Belarus" },
  { id: "belgium", name: "Belgium" },
  { id: "belize", name: "Belize" },
  { id: "benin", name: "Benin" },
  { id: "bermuda", name: "Bermuda" },
  { id: "bhutan", name: "Bhutan" },
  { id: "bolivia", name: "Bolivia" },
  { id: "bonaire", name: "Bonaire" },
  { id: "bosnia_and_herzegovina", name: "Bosnia and Herzegovina" },
  { id: "botswana", name: "Botswana" },
  { id: "bouvet_island", name: "Bouvet Island" },
  { id: "brazil", name: "Brazil" },
  { id: "brunei_darussalam", name: "Brunei Darussalam" },
  { id: "bulgaria", name: "Bulgaria" },
  { id: "burkina_faso", name: "Burkina Faso" },
  { id: "burundi", name: "Burundi" },
  { id: "cabo_verde", name: "Cabo Verde" },
  { id: "cambodia", name: "Cambodia" },
  { id: "cameroon", name: "Cameroon" },
  { id: "canada", name: "Canada" },
  { id: "cayman_islands", name: "Cayman Islands" },
  { id: "central_african_republic", name: "Central African Republic" },
  { id: "chad", name: "Chad" },
  { id: "chile", name: "Chile" },
  { id: "china", name: "China" },
  { id: "christmas_island", name: "Christmas Island" },
  { id: "cocos_islands", name: "Cocos Islands" },
  { id: "colombia", name: "Colombia" },
  { id: "comoros", name: "Comoros" },
  { id: "congo", name: "Congo" },
  { id: "congo", name: "Congo" },
  { id: "cook_islands", name: "Cook Islands" },
  { id: "costa_rica", name: "Costa Rica" },
  { id: "cote_d'ivoire", name: "Cote d'Ivoire" },
  { id: "croatia", name: "Croatia" },
  { id: "cuba", name: "Cuba" },
  { id: "curacao", name: "Curacao" },
  { id: "cyprus", name: "Cyprus" },
  { id: "czech_republic", name: "Czech Republic" },
  { id: "denmark", name: "Denmark" },
  { id: "djibouti", name: "Djibouti" },
  { id: "dominica", name: "Dominica" },
  { id: "dominican_republic", name: "Dominican Republic" },
  { id: "ecuador", name: "Ecuador" },
  { id: "egypt", name: "Egypt" },
  { id: "el_salvador", name: "El Salvador" },
  { id: "equatorial_guinea", name: "Equatorial Guinea" },
  { id: "eritrea", name: "Eritrea" },
  { id: "estonia", name: "Estonia" },
  { id: "ethiopia", name: "Ethiopia" },
  { id: "falkland_islands", name: "Falkland Islands" },
  { id: "faroe_islands", name: "Faroe Islands" },
  { id: "fiji", name: "Fiji" },
  { id: "finland", name: "Finland" },
  { id: "france", name: "France" },
  { id: "french_guiana", name: "French Guiana" },
  { id: "french_polynesia", name: "French Polynesia" },
  { id: "french_southern_territories", name: "French Southern Territories" },
  { id: "gabon", name: "Gabon" },
  { id: "gambia", name: "Gambia" },
  { id: "georgia", name: "Georgia" },
  { id: "germany", name: "Germany" },
  { id: "ghana", name: "Ghana" },
  { id: "gibraltar", name: "Gibraltar" },
  { id: "greece", name: "Greece" },
  { id: "greenland", name: "Greenland" },
  { id: "grenada", name: "Grenada" },
  { id: "guadeloupe", name: "Guadeloupe" },
  { id: "guam", name: "Guam" },
  { id: "guatemala", name: "Guatemala" },
  { id: "guernsey", name: "Guernsey" },
  { id: "guinea", name: "Guinea" },
  { id: "guinea-bissau", name: "Guinea-Bissau" },
  { id: "guyana", name: "Guyana" },
  { id: "haiti", name: "Haiti" },
  { id: "heard_and_mcdonald_islands", name: "Heard and McDonald Islands" },
  { id: "holy_see", name: "Holy See" },
  { id: "honduras", name: "Honduras" },
  { id: "hong_kong", name: "Hong Kong" },
  { id: "hungary", name: "Hungary" },
  { id: "iceland", name: "Iceland" },
  { id: "india", name: "India" },
  { id: "indonesia", name: "Indonesia" },
  { id: "iran", name: "Iran" },
  { id: "iraq", name: "Iraq" },
  { id: "ireland", name: "Ireland" },
  { id: "isle_of_man", name: "Isle of Man" },
  { id: "israel", name: "Israel" },
  { id: "italy", name: "Italy" },
  { id: "jamaica", name: "Jamaica" },
  { id: "japan", name: "Japan" },
  { id: "jersey", name: "Jersey" },
  { id: "jordan", name: "Jordan" },
  { id: "kazakhstan", name: "Kazakhstan" },
  { id: "kenya", name: "Kenya" },
  { id: "kiribati", name: "Kiribati" },
  { id: "korea", name: "Korea" },
  { id: "korea", name: "Korea" },
  { id: "kuwait", name: "Kuwait" },
  { id: "kyrgyzstan", name: "Kyrgyzstan" },
  { id: "lao_peoples", name: "Lao People's" },
  { id: "latvia", name: "Latvia" },
  { id: "lebanon", name: "Lebanon" },
  { id: "lesotho", name: "Lesotho" },
  { id: "liberia", name: "Liberia" },
  { id: "libya", name: "Libya" },
  { id: "liechtenstein", name: "Liechtenstein" },
  { id: "lithuania", name: "Lithuania" },
  { id: "luxembourg", name: "Luxembourg" },
  { id: "macao", name: "Macao" },
  { id: "macedonia", name: "Macedonia" },
  { id: "madagascar", name: "Madagascar" },
  { id: "malawi", name: "Malawi" },
  { id: "malaysia", name: "Malaysia" },
  { id: "maldives", name: "Maldives" },
  { id: "mali", name: "Mali" },
  { id: "malta", name: "Malta" },
  { id: "marshall_islands", name: "Marshall Islands" },
  { id: "martinique", name: "Martinique" },
  { id: "mauritania", name: "Mauritania" },
  { id: "mauritius", name: "Mauritius" },
  { id: "mayotte", name: "Mayotte" },
  { id: "mexico", name: "Mexico" },
  { id: "micronesia", name: "Micronesia" },
  { id: "moldova", name: "Moldova" },
  { id: "monaco", name: "Monaco" },
  { id: "mongolia", name: "Mongolia" },
  { id: "montenegro", name: "Montenegro" },
  { id: "montserrat", name: "Montserrat" },
  { id: "morocco", name: "Morocco" },
  { id: "mozambique", name: "Mozambique" },
  { id: "myanmar", name: "Myanmar" },
  { id: "namibia", name: "Namibia" },
  { id: "nauru", name: "Nauru" },
  { id: "nepal", name: "Nepal" },
  { id: "netherlands", name: "Netherlands" },
  { id: "new_caledonia", name: "New Caledonia" },
  { id: "new_zealand", name: "New Zealand" },
  { id: "nicaragua", name: "Nicaragua" },
  { id: "niger", name: "Niger" },
  { id: "nigeria", name: "Nigeria" },
  { id: "niue", name: "Niue" },
  { id: "norfolk_island", name: "Norfolk Island" },
  { id: "northern_mariana_islands", name: "Northern Mariana Islands" },
  { id: "norway", name: "Norway" },
  { id: "oman", name: "Oman" },
  { id: "pakistan", name: "Pakistan" },
  { id: "palau", name: "Palau" },
  { id: "palestine", name: "Palestine" },
  { id: "panama", name: "Panama" },
  { id: "papua_new_guinea", name: "Papua New Guinea" },
  { id: "paraguay", name: "Paraguay" },
  { id: "peru", name: "Peru" },
  { id: "philippines", name: "Philippines" },
  { id: "pitcairn", name: "Pitcairn" },
  { id: "poland", name: "Poland" },
  { id: "portugal", name: "Portugal" },
  { id: "puerto_rico", name: "Puerto Rico" },
  { id: "qatar", name: "Qatar" },
  { id: "reunion", name: "Reunion" },
  { id: "romania", name: "Romania" },
  { id: "russian_federation", name: "Russian Federation" },
  { id: "rwanda", name: "Rwanda" },
  { id: "saint_barthelemy", name: "Saint Barthelemy" },
  { id: "saint_helena", name: "Saint Helena" },
  { id: "saint_kitts_and_nevis", name: "Saint Kitts and Nevis" },
  { id: "saint_lucia", name: "Saint Lucia" },
  { id: "saint_martin", name: "Saint Martin" },
  { id: "saint_pierre_and_miquelon", name: "Saint Pierre and Miquelon" },
  {
    id: "saint_vincent_and_the_grenadines",
    name: "Saint Vincent and the Grenadines",
  },
  { id: "samoa", name: "Samoa" },
  { id: "san_marino", name: "San Marino" },
  { id: "sao_tome_and_principe", name: "Sao Tome and Principe" },
  { id: "saudi_arabia", name: "Saudi Arabia" },
  { id: "senegal", name: "Senegal" },
  { id: "serbia", name: "Serbia" },
  { id: "seychelles", name: "Seychelles" },
  { id: "sierra_leone", name: "Sierra Leone" },
  { id: "singapore", name: "Singapore" },
  { id: "sint_maarten", name: "Sint Maarten" },
  { id: "slovakia", name: "Slovakia" },
  { id: "slovenia", name: "Slovenia" },
  { id: "solomon_islands", name: "Solomon Islands" },
  { id: "somalia", name: "Somalia" },
  { id: "south_africa", name: "South Africa" },
  { id: "south_georgia", name: "South Georgia" },
  { id: "south_sudan", name: "South Sudan" },
  { id: "spain", name: "Spain" },
  { id: "sri_lanka", name: "Sri Lanka" },
  { id: "sudan", name: "Sudan" },
  { id: "suriname", name: "Suriname" },
  { id: "svalbard_and_jan mayen", name: "Svalbard and Jan Mayen" },
  { id: "swaziland", name: "Swaziland" },
  { id: "sweden", name: "Sweden" },
  { id: "switzerland", name: "Switzerland" },
  { id: "syrian_arab_republic", name: "Syrian Arab Republic" },
  { id: "taiwan", name: "Taiwan" },
  { id: "tajikistan", name: "Tajikistan" },
  { id: "tanzania", name: "Tanzania" },
  { id: "thailand", name: "Thailand" },
  { id: "timor_leste", name: "Timor Leste" },
  { id: "togo", name: "Togo" },
  { id: "tokelau", name: "Tokelau" },
  { id: "tonga", name: "Tonga" },
  { id: "trinidad_and_tobago", name: "Trinidad and Tobago" },
  { id: "tunisia", name: "Tunisia" },
  { id: "turkey", name: "Turkey" },
  { id: "turkmenistan", name: "Turkmenistan" },
  { id: "turks_and_caicos islands", name: "Turks and Caicos Islands" },
  { id: "tuvalu", name: "Tuvalu" },
  { id: "uganda", name: "Uganda" },
  { id: "ukraine", name: "Ukraine" },
  { id: "united_arab_emirates", name: "United Arab Emirates" },
  { id: "united_kingdom", name: "United Kingdom" },
  { id: "united_states_of america", name: "United States of America" },
  { id: "uruguay", name: "Uruguay" },
  { id: "uzbekistan", name: "Uzbekistan" },
  { id: "vanuatu", name: "Vanuatu" },
  { id: "venezuela", name: "Venezuela" },
  { id: "viet_nam", name: "Viet Nam" },
  { id: "virgin_islands", name: "Virgin Islands" },
  { id: "virgin_islands", name: "Virgin Islands" },
  { id: "wallis_and_futuna", name: "Wallis and Futuna" },
  { id: "western_sahara", name: "Western Sahara" },
  { id: "yemen", name: "Yemen" },
  { id: "zambia", name: "Zambia" },
  { id: "zimbabwe", name: "Zimbabwe" },
]


export default COUNTRIES